name: Release

on:
  pull_request:
    types: [ closed ]
    branches: [ release ]

jobs:
  RunCIJob:
    uses: ./.github/workflows/ci.yml

  BuildAndPushDockerImage:
    name: Build image
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    needs: [ RunCIJob ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME}}/go-cicd:latest
            ${{ secrets.DOCKERHUB_USERNAME}}/go-cicd:${{ github.sha }}